### ISSUE TITLE
Return timedate?

### ISSUE THREAD

**Issue by maelle** [lorenzwalthert/gitsum#36] opened 2018-02-06 15:51 UTC
Using date, time and timezone. This is a feature request 😸

**Comment by maelle** [comment] 2018-02-06 15:55
Oh no realized that it's what date is?!

**Comment by lorenzwalthert** [comment] 2018-02-06 15:55
Yes, but without the time zone

**Comment by lorenzwalthert** [comment] 2018-02-06 15:56
So it's still in local time. See also #25.

**Comment by lorenzwalthert** [comment] 2018-02-06 15:56
Well haha don't see #25 because it's probably confusing...

**Comment by maelle** [comment] 2018-02-06 15:57
oh ok... will it be in real UTC in the future?

**Comment by lorenzwalthert** [comment] 2018-02-06 16:25
I don't know. I think it's more interesting to know when something was committed in local time, i.e. to analyse whether you commit more in the morning or in the evening. What would be your use case? Maybe we can add an exported helper function to convert to UTC.

**Comment by maelle** [comment] 2018-02-06 16:32
My use case is finding the latest commit in a repo before submission to rOpenSci onboarding, defined by the time at which the onboarding issue was opened.

**Comment by lorenzwalthert** [comment] 2018-02-06 20:22
Since I think you can easily create the variable (and I don't have time to implement that now), I will close and postpone this for now.

**Closed as completed by lorenzwalthert** 2018-02-06 20:22 UTC
Labels: Type: Enhancement, Complexity: Low, Priority: Low, Status: Postponed

**Comment by maelle** [comment] 2018-02-07 13:37
I understand, but I actually do not know what the current timezone columns mean, once I find out maybe I can do a PR for the docs.

**Comment by maelle** [comment] 2018-02-07 14:06
Because I don't trust myself, I'm using `git2r` to retrieve timedate. 😂

**Comment by lorenzwalthert** [comment] 2018-02-08 21:49
I think the problem is that I called this variable `date`. It should be `datetime`. Then it would be consistent with the following code: 
```
add_utc_datetime <- function(log) {
  #assert_detailed_log(log) # internal function
  log %>%
    mutate(utc_datetime = .data$data + hours(-1 * as.numeric(.data$timezone) / 100))
}
```
Does that give the right output in your use case? I will probably rename `date` to `datetime` and then implement and export this function...

**Comment by maelle** [comment] 2018-02-09 14:10
It works perfectly! I feel it'd be easier for you to return that than to document the timezone? In any case thanks a ton!!

**Comment by lorenzwalthert** [comment] 2018-02-09 14:11
yes I think I will switch at some point. Your script may not work then anymore though, so I hope you don't use the variable everywhere... :-)

**Comment by maelle** [comment] 2018-02-09 14:12
Oh good point, so here is what I've now written 😸 

```r
    if(!"datetime" %in% names(report)){
      report <-  dplyr::mutate(report,
                               datetime = date + lubridate::hours(-1 * as.numeric(timezone) / 100))
      
    }
```

**Comment by maelle** [comment] 2018-02-09 19:00
Oh actually one needs to parse hours and minutes

```r
if(!"datetime" %in% names(report)){
      report <-  dplyr::mutate(report,
                               hour = as.numeric(stringr::str_sub(timezone, 1, 3)),
                               minute = as.numeric(stringr::str_sub(timezone, 4, 5)),
                               datetime = date + lubridate::hours(-1 * hour) + lubridate::minutes(-1 * minute))
     report <- dplyr::select(report, - hour, - minute)
      
    }
```

Example of a repo with timezone that have minutes in them https://github.com/ropensci/EML

**Comment by lorenzwalthert** [comment] 2018-02-09 19:01
oh thanks for reporting back here. 😄

**Comment by maelle** [comment] 2018-02-09 19:02
My pleasure! I owe you at least bug reports, this package is so useful.
